# file: .github/workflows/hello-world.yml
name: work1
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm' # ускоряет повторные сборки
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # Ставим зависимости
      - run: make setup
      # Запускаем тесты
      - name: run tests
        if: always()
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      # Запуск линтера
      - uses: makelint
        if: always()
        run: make lint
      - uses: nmpci
        if: always()
        run: npm ci
      - uses: nmptest
        if: always()
        run: npm test
